
CREATE TABLE IF NOT EXISTS Users(
    IdUser INTEGER PRIMARY KEY AUTOINCREMENT,
    UserName TEXT NOT NULL UNIQUE,
    Clave TEXT NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT (DATETIME('NOW', 'LOCALTIME'))
);

