
package Vista;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import Algoritmos.ListaSimple;
import Algoritmos.Nodo;
import Algoritmos.Receta;

/**
 *
 * @author adict
 */
public class GestorRecetas extends javax.swing.JFrame {

    /**
     * Creates new form Receta
     */
    private ListaSimple listaRecetas;
    private Receta receta;
    
    public GestorRecetas() {
        initComponents();
        this.setLocationRelativeTo(null);
        listaRecetas = new ListaSimple();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNombReceta = new javax.swing.JTextField();
        jTextFieldNombIngredientes = new javax.swing.JTextField();
        jSpinnerCantidad = new javax.swing.JSpinner();
        botonIngresar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botonOrdenar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jComboIngredientesModf = new javax.swing.JComboBox<>();
        FondoRecetas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("Nombre de receta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("Ingredientes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 70, 20));

        jTextFieldNombReceta.setBackground(new java.awt.Color(238, 229, 233));
        jTextFieldNombReceta.setForeground(new java.awt.Color(2, 2, 2));
        getContentPane().add(jTextFieldNombReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 150, -1));

        jTextFieldNombIngredientes.setBackground(new java.awt.Color(238, 229, 233));
        jTextFieldNombIngredientes.setForeground(new java.awt.Color(2, 2, 2));
        getContentPane().add(jTextFieldNombIngredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 160, 20));

        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        getContentPane().add(jSpinnerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, -1, -1));

        botonIngresar.setBackground(new java.awt.Color(238, 229, 233));
        botonIngresar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        botonIngresar.setForeground(new java.awt.Color(2, 2, 2));
        botonIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Agregar.png"))); // NOI18N
        botonIngresar.setText("Ingresar");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        botonBuscar.setBackground(new java.awt.Color(238, 229, 233));
        botonBuscar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(2, 2, 2));
        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/BuscarImage.png"))); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jTable1.setBackground(new java.awt.Color(238, 229, 233));
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(2, 2, 2));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Receta", "Ingredientes", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, 210));

        botonOrdenar.setBackground(new java.awt.Color(238, 229, 233));
        botonOrdenar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        botonOrdenar.setForeground(new java.awt.Color(2, 2, 2));
        botonOrdenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/seleccionar.png"))); // NOI18N
        botonOrdenar.setText("Ordenar");
        botonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrdenarActionPerformed(evt);
            }
        });
        getContentPane().add(botonOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 110, 30));

        botonModificar.setBackground(new java.awt.Color(238, 229, 233));
        botonModificar.setForeground(new java.awt.Color(2, 2, 2));
        botonModificar.setText("Modificar");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(botonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jButtonHome.setBackground(new java.awt.Color(238, 229, 233));
        jButtonHome.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jButtonHome.setForeground(new java.awt.Color(2, 2, 2));
        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/home.png"))); // NOI18N
        jButtonHome.setText("Home");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jComboIngredientesModf.setBackground(new java.awt.Color(238, 229, 233));
        jComboIngredientesModf.setForeground(new java.awt.Color(2, 2, 2));
        jComboIngredientesModf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboIngredientesModf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        FondoRecetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/recetas.jpg"))); // NOI18N
        FondoRecetas.setText("jLabel3");
        getContentPane().add(FondoRecetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cargarRecetasEnTabla() {
        String[][] datos = obtenerDatosRecetas();
        String[] columnas = {"Recetas","Ingredientes", "Cantidad"};
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(datos, columnas);
        jTable1.setModel(model);
    }
    private String[][] obtenerDatosRecetas() {
        int cantidadRecetas = listaRecetas.contarRecetas();
        String[][] datos = new String[cantidadRecetas][3];

        Nodo temp = listaRecetas.getCabeza();
        int i = 0;
        while (temp != null) {
            datos[i][0] = temp.getReceta().getNombre();
            datos[i][1] = temp.getReceta().getIngredientes();
            datos[i][2] = temp.getReceta().getCantidad().toString();
            temp = temp.getSiguiente();
            i++;
        }
        return datos;
    }
    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        String nombre = jTextFieldNombReceta.getText();
        String nombreIngrediente = jTextFieldNombIngredientes.getText();
        int cantidadIngredientes = (Integer) jSpinnerCantidad.getValue();

        // Busca si la receta ya existe en la lista
        Receta recetaExistente = listaRecetas.buscarReceta(nombre);

        if (recetaExistente != null) {
            // Si la receta ya existe, añade el nuevo ingrediente
            String nuevosIngredientes = recetaExistente.getIngredientes() + ", " + nombreIngrediente;
            recetaExistente.setIngredientes(nuevosIngredientes);
            recetaExistente.setCantidad(recetaExistente.getCantidad() + cantidadIngredientes); // Opcional: depende de cómo manejes las cantidades
        } else {
            // Si la receta no existe, crea una nueva receta
            recetaExistente = new Receta(nombre, nombreIngrediente, cantidadIngredientes);
            listaRecetas.agregarReceta(recetaExistente);
        }

        // Actualiza la receta en la base de datos
        try {
            int userId = Controlers.UserSession.getInstance().getUserId();
        
            // Verificar si la receta ya existe en la base de datos
            int idReceta = Controlers.RecetaControl.getRecipeId(nombre, userId);
        
        if (idReceta == -1) { // Si no existe, la creamos
            Controlers.RecetaControl.agregoReceta(userId, nombre);
            //JOptionPane.showMessageDialog(this, "Se ha agregado la receta con éxito a la base de datos!");
            
            // Obtener el ID de la receta recién creada para futuros usos si es necesario
            idReceta = Controlers.RecetaControl.getRecipeId(nombre, userId);
        } else {
            //JOptionPane.showMessageDialog(this, "La receta ya existe en la base de datos.");
        }
        
        // Dividir los ingredientes por comas y agregar cada uno a la base de datos
        String[] ingredientesArray = nombreIngrediente.split(",");
        for (String ingrediente : ingredientesArray) {
            ingrediente = ingrediente.trim(); // Elimina espacios en blanco al inicio y al final
            Controlers.RecetaControl.agregarIngrediente(idReceta, ingrediente, String.valueOf(cantidadIngredientes));
        }
        //JOptionPane.showMessageDialog(this, "Ingredientes agregados con éxito a la receta!");
        
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al registrar la receta en la base de datos!");
        }
        
        
        // Muestra un mensaje de confirmación
        JOptionPane.showMessageDialog(this, "Receta guardada con éxito");
    
        // Limpia los campos de texto
        //jTextField1.setText("");
        //jTextArea1.setText("");
    
        // Actualiza la tabla para mostrar la nueva receta (si es necesario)
        cargarRecetasEnTabla();
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        String nombre = jTextFieldNombReceta.getText();
        receta = listaRecetas.buscarReceta(nombre);  // Asigna la receta encontrada a la variable 'receta'

        if (receta != null) {
            jTextFieldNombReceta.setText(receta.getNombre());
            jTextFieldNombIngredientes.setText(receta.getIngredientes());
            llenarComboBoxIngredientes(); //Llena el ComboBox con los ingredientes
        } else {
            //JOptionPane.showMessageDialog(this, "Receta no encontrada");
            jTextFieldNombReceta.setText("");
            jTextFieldNombIngredientes.setText("");
        }
     
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrdenarActionPerformed
        listaRecetas.ordenarRecetasPorNombre();
        // Actualiza la tabla después de ordenar
        cargarRecetasEnTabla();
    }//GEN-LAST:event_botonOrdenarActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        if (receta != null) {
            receta.setIngredientes(jTextFieldNombIngredientes.getText());
            JOptionPane.showMessageDialog(this, "Ingredientes actualizados con éxito");
            cargarRecetasEnTabla();  // Actualiza la tabla para reflejar los cambios
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Primero busque una receta para modificar");
        }
    }//GEN-LAST:event_botonModificarActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorRecetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoRecetas;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonOrdenar;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JComboBox<String> jComboIngredientesModf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldNombIngredientes;
    private javax.swing.JTextField jTextFieldNombReceta;
    // End of variables declaration//GEN-END:variables

    private void llenarComboBoxIngredientes() {
        jComboIngredientesModf.removeAllItems();
        if (receta != null) {
            String[] ingredientes = receta.getIngredientes().split(", "); // Asumiendo que los ingredientes están separados por comas
            for (String ingrediente : ingredientes) {
            jComboIngredientesModf.addItem(ingrediente);
            }
        }
    }
}
