
package Vista;

import Controlers.UserSession;

/**
 *
 * @author jhair
 */
public class HomePage extends javax.swing.JFrame {
    private int userId;
    /**
     * Creates new form HomePage
     */
    public HomePage() {
        int userId1 = this.userId;
        initComponents();
        this.setLocationRelativeTo(null);
        
         UserSession sesion = UserSession.getInstance();  // Corregido
        if (sesion != null) {
            // Acceder a los datos del usuario
            int userId = sesion.getUserId();
            String nombreUsuario = sesion.getUsername();
        
            // Mostrar mensaje de bienvenida
        jLabelBienvenido.setText("Bienvenido, " + nombreUsuario + "!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAgregarReceta = new javax.swing.JButton();
        jButtonRevisar = new javax.swing.JButton();
        jButtonSeleccionar = new javax.swing.JButton();
        jLabelBienvenido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAgregarReceta.setBackground(new java.awt.Color(238, 229, 233));
        jButtonAgregarReceta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAgregarReceta.setForeground(new java.awt.Color(2, 2, 2));
        jButtonAgregarReceta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Agregar.png"))); // NOI18N
        jButtonAgregarReceta.setText("Agregar");
        jButtonAgregarReceta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonAgregarReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarRecetaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 140, 31));

        jButtonRevisar.setBackground(new java.awt.Color(238, 229, 233));
        jButtonRevisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonRevisar.setForeground(new java.awt.Color(2, 2, 2));
        jButtonRevisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/book-marked-fill.png"))); // NOI18N
        jButtonRevisar.setText("Revisar");
        jButtonRevisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRevisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRevisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 140, 30));

        jButtonSeleccionar.setBackground(new java.awt.Color(238, 229, 233));
        jButtonSeleccionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonSeleccionar.setForeground(new java.awt.Color(2, 2, 2));
        jButtonSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/seleccionar.png"))); // NOI18N
        jButtonSeleccionar.setText("Pedidos");
        jButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 140, -1));

        jLabelBienvenido.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelBienvenido.setForeground(new java.awt.Color(238, 229, 233));
        jLabelBienvenido.setText("Bienvenido a RecetarYOU");
        getContentPane().add(jLabelBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 440, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/wallhaven-x6dq2d.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 620));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));
        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 1110, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarActionPerformed
        new GestorPedidos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSeleccionarActionPerformed

    private void jButtonRevisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRevisarActionPerformed
        new RevisarRecetas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRevisarActionPerformed

    private void jButtonAgregarRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarRecetaActionPerformed
        new GestorRecetas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAgregarRecetaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarReceta;
    private javax.swing.JButton jButtonRevisar;
    private javax.swing.JButton jButtonSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBienvenido;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
