CREATE TABLE IF NOT EXISTS Users (
    IdUser INTEGER PRIMARY KEY AUTOINCREMENT,
    UserName TEXT NOT NULL UNIQUE,
    Clave TEXT NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT (DATETIME('NOW', 'LOCALTIME'))
);

CREATE TABLE IF NOT EXISTS Recetas (
    IdReceta INTEGER PRIMARY KEY AUTOINCREMENT,
    IdUser INTEGER NOT NULL,
    NombreReceta TEXT NOT NULL,
    FOREIGN KEY (IdUser) REFERENCES Users (IdUser)
);

CREATE TABLE IF NOT EXISTS Ingredientes (
    IdIngredientes INTEGER PRIMARY KEY AUTOINCREMENT,
    IdReceta INTEGER NOT NULL,
    NombreIngrediente TEXT NOT NULL,
    Cantidad TEXT,
    FOREIGN KEY (IdReceta) REFERENCES Recetas (IdReceta)
);
